update

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -39,7 +39,14 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           name: prod-vpn-app-jar
-          path: target/
+          path: ./target/
+
+      - name: Verify JAR exists
+        run: |
+          if [ ! -f target/*.jar ]; then
+            echo "JAR file not found!"
+            exit 1
+          fi
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
