update

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,6 +21,12 @@ jobs:
       - name: Build project with Maven
         run: mvn clean package -DskipTests
 
+      - name: Upload JAR artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: prod-vpn-app-jar
+          path: target/*.jar
+
   build-docker:
     runs-on: ubuntu-latest
     needs: build-java
@@ -28,6 +34,22 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
+
+      - name: Download JAR artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: prod-vpn-app-jar
+          path: ./target/
+
+      - name: Verify JAR exists
+        run: |
+          if [ ! -f target/*.jar ]; then
+            echo "JAR file not found!"
+            exit 1
+          fi
+
+      - name: List files in target folder
+        run: ls -al target/
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
@@ -57,6 +79,15 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
+
+      - name: Copy Dockerfile to server via SSH
+        uses: appleboy/scp-action@master
+        with:
+          host: ${{ secrets.SSH_HOST }}
+          username: ${{ secrets.SSH_USER }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          source: "Dockerfile"
+          target: "~/app"
 
       - name: Copy docker-compose.yml to server via SSH
         uses: appleboy/scp-action@master
